"""moving is_active to the user table

Revision ID: 2ddb9c2b347b
Revises: f4c999fefc36
Create Date: 2024-06-16 11:39:52.160378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ddb9c2b347b'
down_revision: Union[str, None] = 'f4c999fefc36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_avtive')
    op.add_column('users', sa.Column('is_avtive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_avtive')
    op.add_column('profiles', sa.Column('is_avtive', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
